export type ProviderCatalogDetail = {
  name: string;
  label: string;
  kind: string;
  useCase: string;
  advantage: string;
  disadvantage: string;
  cost: string;
  privacy: string;
  lockIn: string;
  keyMode: string;
  capabilities: string[];
};

export const fallbackProviderCatalog: ProviderCatalogDetail[] = [
  {
    name: "ollama",
    label: "Ollama",
    kind: "ollama",
    useCase: "Local chat, RAG validation, and offline development.",
    advantage: "Runs on operator hardware and keeps prompts local by default.",
    disadvantage: "Quality and latency depend on the installed local model and machine resources.",
    cost: "No provider token charge; local compute cost only.",
    privacy: "Local-first. Data stays on the operator machine unless another route is selected.",
    lockIn: "Low. Open local runtime with swappable models.",
    keyMode: "No external API key.",
    capabilities: ["chat", "local", "rag", "offline", "no-key"],
  },
  {
    name: "openai",
    label: "OpenAI",
    kind: "openai-compatible",
    useCase: "General assistants, tool use, structured output, and multimodal workflows.",
    advantage: "Broad model family and mature API patterns.",
    disadvantage: "External cloud dependency and provider-specific feature contracts.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing. Tenant policy and data controls must be reviewed before production use.",
    lockIn: "Medium. OpenAI-compatible APIs help, but advanced features can be provider-specific.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "tools", "vision", "embeddings", "structured-output"],
  },
  {
    name: "anthropic",
    label: "Anthropic",
    kind: "anthropic",
    useCase: "Long-context analysis, writing, research, and cautious assistant workflows.",
    advantage: "Strong instruction following and long document handling.",
    disadvantage: "Non OpenAI-compatible native API shape requires an adapter.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing with provider retention and policy settings to review.",
    lockIn: "Medium. Native message/tool formats need provider-aware routing.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "long-context", "tools", "vision"],
  },
  {
    name: "google_gemini",
    label: "Google Gemini",
    kind: "google",
    useCase: "Multimodal assistants and Google AI Studio style prototyping.",
    advantage: "Strong multimodal coverage and broad context options.",
    disadvantage: "API and quota behavior differs from OpenAI-compatible routes.",
    cost: "Cloud usage pricing by model, token volume, and modality.",
    privacy: "Cloud processing. Workspace policy should define data classification before use.",
    lockIn: "Medium. Native Google model features require provider-specific handling.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "vision", "long-context", "multimodal"],
  },
  {
    name: "xai_grok",
    label: "xAI Grok",
    kind: "openai-compatible",
    useCase: "OpenAI-compatible chat routes for Grok models.",
    advantage: "Can reuse OpenAI-compatible routing infrastructure.",
    disadvantage: "Provider availability and model behavior need live validation.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing with provider policy review required.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "openai-compatible"],
  },
  {
    name: "zhipu_glm",
    label: "Zhipu GLM",
    kind: "openai-compatible",
    useCase: "GLM-family chat through an OpenAI-compatible adapter.",
    advantage: "Regional provider option with familiar transport.",
    disadvantage: "Compliance, availability, and language behavior need route-specific testing.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing. Region and data-transfer review required.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "openai-compatible"],
  },
  {
    name: "moonshot_kimi",
    label: "Moonshot Kimi",
    kind: "openai-compatible",
    useCase: "Long-context chat and document workflows through Kimi models.",
    advantage: "OpenAI-compatible route surface for long-context use cases.",
    disadvantage: "Provider-specific limits and regional compliance need validation.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing. Region and retention policy review required.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "long-context", "openai-compatible"],
  },
  {
    name: "mistral",
    label: "Mistral",
    kind: "openai-compatible",
    useCase: "EU-friendly chat, agents, and cost-sensitive model routing.",
    advantage: "Fast models and OpenAI-compatible integration options.",
    disadvantage: "Model-specific tool and JSON behavior still needs acceptance testing.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing with regional deployment options to evaluate.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "tools", "openai-compatible"],
  },
  {
    name: "cohere",
    label: "Cohere",
    kind: "cohere",
    useCase: "Enterprise search, reranking, embeddings, and retrieval-heavy applications.",
    advantage: "Strong retrieval and reranking primitives.",
    disadvantage: "Native API differs from chat-completion style routes.",
    cost: "Cloud usage pricing by endpoint and volume.",
    privacy: "Cloud processing. Enterprise controls should be reviewed.",
    lockIn: "Medium. Retrieval primitives are provider-specific.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "embeddings", "rerank", "search"],
  },
  {
    name: "deepseek",
    label: "DeepSeek",
    kind: "openai-compatible",
    useCase: "Cost-sensitive chat and coding routes with OpenAI-compatible transport.",
    advantage: "Useful as a low-cost cloud route candidate.",
    disadvantage: "Availability, data policy, and model behavior require live checks.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing with policy and region review required.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "code", "openai-compatible"],
  },
  {
    name: "groq",
    label: "Groq",
    kind: "openai-compatible",
    useCase: "Low-latency chat routes for interactive flows.",
    advantage: "Optimized for speed-sensitive inference.",
    disadvantage: "Model selection and context limits need route-level validation.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing with provider policy review required.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "low-latency", "openai-compatible"],
  },
  {
    name: "together",
    label: "Together AI",
    kind: "openai-compatible",
    useCase: "Open model hosting, experimentation, and custom inference routes.",
    advantage: "Broad open-model catalog behind familiar APIs.",
    disadvantage: "Model quality and limits vary by selected hosted model.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing. Hosted model and data policy review required.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "open-models", "openai-compatible"],
  },
  {
    name: "fireworks",
    label: "Fireworks",
    kind: "openai-compatible",
    useCase: "Fast hosted open-model inference and custom model endpoints.",
    advantage: "Good fit for open-model production routing.",
    disadvantage: "Requires provider-specific capacity and model validation.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing. Endpoint policy and model hosting terms apply.",
    lockIn: "Low to medium through OpenAI-compatible transport.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "open-models", "openai-compatible"],
  },
  {
    name: "replicate",
    label: "Replicate",
    kind: "replicate",
    useCase: "Hosted model experiments across text, image, and specialist models.",
    advantage: "Large hosted model marketplace.",
    disadvantage: "Per-model inputs and outputs need custom adapters.",
    cost: "Cloud usage pricing by model runtime and provider rules.",
    privacy: "Cloud processing. Model owner and hosting terms need review.",
    lockIn: "Medium. Prediction contracts vary by model.",
    keyMode: "Workspace secret reference.",
    capabilities: ["hosted-models", "multimodal", "experiments"],
  },
  {
    name: "huggingface",
    label: "Hugging Face Inference",
    kind: "huggingface",
    useCase: "Hosted open models, embeddings, and model evaluation experiments.",
    advantage: "Broad open-source ecosystem and model discovery.",
    disadvantage: "Endpoint behavior varies by model and deployment type.",
    cost: "Cloud usage pricing by endpoint and compute tier.",
    privacy: "Cloud processing unless using self-hosted endpoints.",
    lockIn: "Low to medium. Model assets are portable, endpoint contracts vary.",
    keyMode: "Workspace secret reference.",
    capabilities: ["open-models", "embeddings", "hosted-inference"],
  },
  {
    name: "openrouter",
    label: "OpenRouter",
    kind: "openai-compatible",
    useCase: "Brokered access to many hosted model providers.",
    advantage: "Single OpenAI-compatible route can test multiple models.",
    disadvantage: "Adds a broker dependency and provider-specific behavior still varies.",
    cost: "Brokered cloud usage pricing by selected model.",
    privacy: "Cloud processing through a broker and upstream provider.",
    lockIn: "Medium. Easy model switching, but broker policies matter.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "model-broker", "openai-compatible"],
  },
  {
    name: "perplexity",
    label: "Perplexity",
    kind: "openai-compatible",
    useCase: "Search-grounded and research-style answer routes.",
    advantage: "Useful for answers that need web-style retrieval behavior.",
    disadvantage: "Grounding behavior needs careful citation and policy checks.",
    cost: "Cloud usage pricing by model and token volume.",
    privacy: "Cloud processing with search-grounding policy review required.",
    lockIn: "Medium. Search-grounded behavior is provider-specific.",
    keyMode: "Workspace secret reference.",
    capabilities: ["chat", "search-grounded", "openai-compatible"],
  },
  {
    name: "azure_openai",
    label: "Azure OpenAI",
    kind: "azure-openai",
    useCase: "Enterprise Azure deployments, private networking, and managed governance.",
    advantage: "Fits Azure identity, networking, and compliance controls.",
    disadvantage: "Deployment names and regional capacity require Azure-specific configuration.",
    cost: "Azure metered usage by deployment and model.",
    privacy: "Cloud processing in configured Azure region and tenant controls.",
    lockIn: "Medium. Azure deployment contract is provider-specific.",
    keyMode: "Azure key, Entra identity, or secret reference.",
    capabilities: ["chat", "enterprise", "azure", "private-networking"],
  },
  {
    name: "google_vertex_ai",
    label: "Google Vertex AI",
    kind: "vertex-ai",
    useCase: "GCP enterprise model routing, governance, and regional deployment.",
    advantage: "Integrates with GCP IAM and Vertex operations.",
    disadvantage: "Requires GCP project, region, and service account setup.",
    cost: "GCP metered usage by model and endpoint.",
    privacy: "Cloud processing in configured GCP controls.",
    lockIn: "Medium. Vertex APIs and IAM are provider-specific.",
    keyMode: "Service account or workload identity.",
    capabilities: ["chat", "enterprise", "gcp", "multimodal"],
  },
  {
    name: "aws_bedrock",
    label: "AWS Bedrock",
    kind: "bedrock",
    useCase: "AWS enterprise model access, cross-provider routing, and governance.",
    advantage: "IAM-native access to multiple foundation model families.",
    disadvantage: "AWS-specific request signing, regions, and model IDs are required.",
    cost: "AWS metered usage by model and region.",
    privacy: "Cloud processing in configured AWS region and account controls.",
    lockIn: "Medium. Bedrock APIs and IAM are provider-specific.",
    keyMode: "AWS IAM role or access key secret reference.",
    capabilities: ["chat", "enterprise", "aws", "model-broker"],
  },
  {
    name: "vllm",
    label: "vLLM",
    kind: "openai-compatible",
    useCase: "Self-hosted OpenAI-compatible inference for production clusters.",
    advantage: "Portable open-model serving with high throughput options.",
    disadvantage: "Requires GPU capacity, scaling, and operations ownership.",
    cost: "Infrastructure cost only; no external token charge.",
    privacy: "Self-hosted when deployed inside operator infrastructure.",
    lockIn: "Low. OpenAI-compatible transport and portable model weights.",
    keyMode: "Internal endpoint token or network policy.",
    capabilities: ["chat", "self-hosted", "open-models", "openai-compatible"],
  },
  {
    name: "huggingface_tgi",
    label: "Hugging Face TGI",
    kind: "openai-compatible",
    useCase: "Self-hosted text-generation inference for open models.",
    advantage: "Operationally direct path for serving Hugging Face models.",
    disadvantage: "Requires model hosting, GPU capacity, and route operations.",
    cost: "Infrastructure cost only; no external token charge when self-hosted.",
    privacy: "Self-hosted when deployed inside operator infrastructure.",
    lockIn: "Low. Model weights are portable, serving APIs need adapter checks.",
    keyMode: "Internal endpoint token or network policy.",
    capabilities: ["chat", "self-hosted", "open-models"],
  },
];

export function getProviderCatalogDetail(name?: string | null): ProviderCatalogDetail {
  const normalized = normalizeProviderName(name);
  return (
    fallbackProviderCatalog.find((provider) => provider.name === normalized) ?? {
      name: normalized || "unknown",
      label: titleCaseProviderName(normalized || "Unknown provider"),
      kind: "unknown",
      useCase: "Provider discovered from the platform API.",
      advantage: "Available through the active backend contract.",
      disadvantage: "No local comparison metadata has been added yet.",
      cost: "Pricing unavailable until price snapshots are returned.",
      privacy: "Review provider data policy before production use.",
      lockIn: "Unknown until adapter and portability are documented.",
      keyMode: "Workspace secret reference.",
      capabilities: ["provider-api"],
    }
  );
}

export function normalizeProviderName(name?: string | null) {
  return (name ?? "").trim().toLowerCase().replaceAll("-", "_").replaceAll(" ", "_");
}

function titleCaseProviderName(name: string) {
  return name
    .replaceAll("_", " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
